# docker stack deploy -c stack.yml deploy_services
# optional pgadmin container

networks:
  virtual-local-network:
services:
  delta:
    image: deltaio/delta-docker:latest
    ports:
    - "8888:8888"
    - "8889:8889"
    networks:
    - virtual-local-network   
    deploy:
     replicas: 1
     restart_policy:
       condition: on-failure
    volumes:
    - C:\Users\Natsai\Documents\Credit_Landing_Project\:/opt/spark/work-dir/
  pg_sql_dw:
    container_name: pg_sql_dw
    image: ctnatsai/postgresql:latest
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: credit_landing
    ports:
    - "5438:5432"
    networks:
    - virtual-local-network
    volumes:
    - pg_sql_dw:/var/lib/postgresql/data
    deploy:
     restart_policy:
       condition: on-failure
  pgadmin:
    image: ctnatsai/pgadmin:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 5up3rS3cr3t!
    ports:
      - "8180:80"
    networks:
      - virtual-local-network
    deploy:
      restart_policy:
        condition: on-failure
  pg_grafana:
    container_name: pg_grafana
    image: ctnatsai/postgresql:latest
    environment:
      POSTGRES_DB: grafana_logs_db
      POSTGRES_USER: grafana_user
      POSTGRES_PASSWORD: grafana_pwd
    ports:
      - "5499:5432"
    networks:
      - virtual-local-network
    volumes:
      - pg_grafana:/var/lib/postgresql/data
  grafana:
    container_name: grafana
    image: ctnatsai/grafana:latest
    user: "0:0"
    environment:
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: pg_grafana:5432
      GF_DATABASE_NAME: grafana_logs_db
      GF_DATABASE_USER: grafana_user
      GF_DATABASE_PASSWORD: grafana_pwd
      GF_DATABASE_SSL_MODE: disable
    restart: unless-stopped
    depends_on:
        - pg_grafana
    ports:
      - 3111:3000
    networks:
      - virtual-local-network
    volumes:
      - C:\Users\Natsai\Documents\Credit_Landing_Project\grafana\:/var/lib/grafana

volumes:
  pg_grafana:
    driver: local
  pg_sql_dw:
    driver: local
  # grafana:
  #   driver: local
  # landing_zone:
  #   driver: local

  # adminer:
  #   image: adminer:latest
  #   ports:
  #   - "8080:8080/tcp"
  #   networks:
  #   - virtual-local-network
  #   deploy:
  #    restart_policy:
  #      condition: on-failure
